version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=airline_db
      - POSTGRES_USER=airline_user
      - POSTGRES_PASSWORD=airline_password
    ports:
      - "5433:5432" #to avoid conflicts

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn airline_integration_service.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://airline_user:airline_password@db:5432/airline_db
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-insecure-change-me-in-production! 
      - DEBUG=True 

 

volumes:
  postgres_data: 